stages:
  - test
  - build
  - docs


# use python as base image unless stated otherwise
image: python:latest

################################
# configure python package cache
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

docs:
  stage: build
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install mkdocs mkdocs-material
    - mkdocs build
  artifacts:
    paths:
      - site

# build Gitlab pages documentation
pages:
  image: alpine:latest
  stage: docs
  # disable cache for this job
  cache: {}
  only:
    - develop
    - master
  script:
    - cp -r site public
  artifacts:
    paths:
      - public
