version: 2.1
commands:
  calculate-tag-name:
    description: "Calculates the target tag name for Docker image"
    parameters:
      distro:
        type: string
    steps:
      - run:
          name: Calculate tag to set for the built Docker image
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then TAG_VERSION=latest; else TAG_VERSION=$CIRCLE_BRANCH; fi
            if [ "<< parameters.distro >>" = "ubuntu" ]; then TAG_DISTRO=""; else TAG_DISTRO=-<< parameters.distro >>; fi
            echo "export IMAGE_TAG=$TAG_VERSION$TAG_DISTRO" >> $BASH_ENV

jobs:
  build-alpine-image:
    environment:
      IMAGE_NAME: guillaumedsde/qbittorrent-openvpn
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - calculate-tag-name:
          distro: alpine
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile.alpine .
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push image
          command: docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build-images:
    jobs:
      - build-alpine-image:
          context: dockerhub
          filters:
            branches:
              only:
                - master
